---
title: "NoteBook Metkuan"
output: html_notebook
---

# Student Performance Metrics Dataset

### Importing Library

```{r}
library(tidyverse)
library(lubridate)
library(skimr)
library(corrplot)
library(caret)
library(randomForest)
```

### Initiate a dataframe

```{r}
df <- Student_Performance_Metrics_Dataset
```

### Data Exploration

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
head(df)
```

```{r}
dim(df)
```

```{r}
sapply(df, class)
```

### Char data processing

```{r}
char_data <- df[ , sapply(df, is.character)]
char_cols <- names(df)[sapply(df, is.character)]
print(char_cols)
```

Diketahui bahwa Departemen, Gender, Income, Hometown, Preparation, Gaming, Attendance, Job, Extra, Semester adalah kategorik

```{r}
head(char_data)
```

Cek kolom distinct

```{r}
sapply(char_data, unique)
```

Standarisasi

```{r}
library(dplyr)
library(stringr)
df <- df %>%
  mutate(across(where(is.character), ~str_trim(.))) %>%
  mutate(across(where(is.character), ~str_to_title(.)))
```

Konversi

```{r}
factor_cols <- c("Department", "Gender", "Income", "Hometown", "Preparation", "Gaming", "Attendance", "Job", "Extra", "Semester")
```

```{r}
df[factor_cols] <- lapply(df[factor_cols], as.factor)
```

Reordering

```{r}
# Income: Low < Lower Middle < Upper Middle < High
df$Income <- factor(df$Income, levels = c(
  "Low (Below 15,000)",
  "Lower Middle (15,000-30,000)",
  "Upper Middle (30,000-50,000)",
  "High (Above 50,000)"
), ordered = TRUE)

# Preparation and Gaming time
df$Preparation <- factor(df$Preparation, levels = c(
  "0-1 Hour", "2-3 Hours", "More Than 3 Hours"
), ordered = TRUE)

df$Gaming <- factor(df$Gaming, levels = c(
  "0-1 Hour", "2-3 Hours", "More Than 3 Hours"
), ordered = TRUE)

# Attendance
df$Attendance <- factor(df$Attendance, levels = c(
  "Below 40%", "40%-59%", "60%-79%", "80%-100%"
), ordered = TRUE)

# Semester (custom sort by number)
df$Semester <- factor(df$Semester, levels = paste0(1:12, "th"), ordered = TRUE)
```

Cek data yang sudah dibersihkan

```{r}
str(df)
```

```{r}
summary(df)
```

### 
